/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_messageWindow (void);
GtkWidget* create_configWindow1 (void);
GtkWidget* create_initialWindow (void);
GtkWidget* create_downloadWindow (void);
GtkWidget* create_downloadDialog (void);
GtkWidget* create_downloadfilechooserdialog (void);
GtkWidget* create_logfileChooserdialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_readNotifyDialog (void);
GtkWidget* create_viewWindow (void);
GtkWidget* create_sendFailDialog (void);
GtkWidget* create_attachFileEditor (void);
GtkWidget* create_ipmsgDownloadOverWrite (void);
GtkWidget* create_downloadMonitor (void);
GtkWidget* create_passwdWindow (void);
GtkWidget* create_absenceEditor (void);
GtkWidget* create_DownloadConfirmDialog (void);
GtkWidget* create_downLoadFailDialog (void);
GtkWidget* create_downloadOpenDirOnlydialog (void);
GtkWidget* create_viewConfigWindow (void);
GtkWidget* create_userlistPopUpMenu (void);
GtkWidget* create_clientInfoWindow (void);
GtkWidget* create_securityConfig (void);
GtkWidget* create_passwdDialog (void);
GtkWidget* create_errorDialog (void);
